BOILERPLATE_STRINGS = {
    'about us',
    'about',
    'accessibility',
    'ad',
    'advertise with us',
    'advertise',
    'advertisement',
    'advertising',
    'all rights reserved',
    'australia',
    'bussiness',
    'books',
    'career',
    'careers',
    'close',
    'comments',
    'contact us',
    'contact',
    'content policy',
    'cookie policy',
    'copyright',
    'cricket',
    'culture',
    'education',
    'email',
    'entertainment',
    'events',
    'facebook',
    'fashion',
    'features',
    'follow us',
    'food',
    'football',
    'golf',
    'health',
    'help',
    'home',
    'instagram',
    'india',
    'jobs',
    'latest news',
    'lifestyle',
    'log in',
    'login',
    'menu',
    'money',
    'more',
    'movies',
    'music',
    'news',
    'newsletter',
    'newsletters',
    'opinion',
    'photos',
    'pinterest',
    'podcasts',
    'policy',
    'politics',
    'print',
    'privacy',
    'privacy policy',
    'reddit',
    'register',
    'reviews',
    'schedule'
    'science',
    'search',
    'share',
    'shop',
    'sign up',
    'signup',
    'sitemap',
    'skip to content',
    'skip to main content',
    'sport',
    'sports',
    'style',
    'subscribe',
    'tech',
    'tennis',
    'terms & conditions',
    'terms of service',
    'terms of use',
    'terms',
    'travel',
    'trending',
    'tv',
    'twitter',
    'video',
    'videos',
    'weather',
    'world',
    'youtube'
}

BOILERPLATE_CLASSES_IDS = {
    'advertising',
    'bold',
    'breadcrumb',
    'breadcrumbs',
    'btn',
    'button',
    'caption',
    'close',
    'col-md-4',
    'collapse',
    'comments',
    'container',
    'copyright',
    'credit',
    'current',
    'current-menu-parent',
    'current-post-ancestor',
    'd-none',
    'description',
    'dropdown',
    'dropdown-menu',
    'email',
    'facebook',
    'first',
    'footer',
    'footer-copyright',
    'footer-links',
    'header',
    'header-wrapper',
    'headline',
    'hidden',
    'hide',
    'item',
    'last',
    'link',
    'list-unstyled',
    'login',
    'logo',
    'main-navigation',
    'masthead',
    'menu',
    'menu-item',
    'menu-item-has-children',
    'menu-item-object-category',
    'menu-item-object-custom',
    'menu-item-object-page',
    'menu-item-type-custom',
    'menu-item-type-post_type',
    'menu-item-type-taxonomy',
    'mol-ads-cmp',
    'mol-ads-cmp--modal',
    'mol-ads-cmp--modal-body',
    'mol-ads-cmp--modal-content',
    'mol-ads-cmp--modal-dialog',
    'mol-ads-cmp--settings',
    'mol-ads-cmp--settings-consent',
    'mol-ads-cmp--settings-consent-name',
    'mol-ads-cmp--settings-consent-policy',
    'mol-ads-cmp--settings-consents',
    'mol-ads-cmp--settings-functional',
    'mol-ads-cmp--tab-body',
    'mol-ads-cmp--tabs-container',
    'more',
    'name',
    'nav',
    'navbar-collapse',
    'navbar-nav',
    'nav-link',
    'navigation',
    'news',
    'no-js',
    'ot-sdk-show-settings',
    'page-header',
    'pinterest',
    'search',
    'search-form',
    'screen-reader-text',
    'share',
    'sidebar',
    'site-footer',
    'site-header',
    'skip-link',
    'social',
    'sr-only',
    'sub-menu',
    'text-center',
    'title',
    'twitter',
    'twitter-tweet',
    'vendor-name',
    'vendor-privacy-policy',
    'vendor-status-label',
    'video',
    'widget',
    'mol-ads-cmp--settings-consent',
}
